[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "abacus"

[project]
name = "abacus-icalc"
authors = [
    {name = "Aleksandar Radivojevic", email = "rzhw3h@gmail.com"}
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Environment :: Console",
    "Framework :: IPython"
]
dynamic = ["version", "description"]
dependencies = [
    "ipython ~= 7.21",
    "sympy ~= 1.10",
]

[project.scripts]
abacus = "abacus:main"

[project.gui-scripts]
abacus-gui = "abacus:main_gui"

[project.urls]
Home = "https://sandorex.github.io/abacus"
Source = "https://github.com/sandorex/abacus"
